TT:
  name: "t#bar{t}"
  color: "kGreen-3"  # eliminates need for plot.yaml
  datasets:
    - TTto2L2Nu
    - TTtoLNu2Q
    - TTto4Q

TT_Inclusive:
  name: "t#bar{t} Inclusive"
  color: "kGreen-3"
  datasets:
    - TT

ST: # New 2025Skim have different ST names?
  name: "ST"
  color: "kPink+1"
  datasets:
    # - ST_s_channel_antitop_4f_leptonDecays
    # - ST_s_channel_top_4f_leptonDecays
    # - ST_t_channel_antitop_4f_InclusiveDecays
    # - ST_t_channel_top_4f_InclusiveDecays
    # - ST_tW_antitop_2L2Nu
    # - ST_tW_antitop_4Q
    # - ST_tW_antitop_LNu2Q
    # - ST_tW_top_2L2Nu
    # - ST_tW_top_4Q
    # - ST_tW_top_LNu2Q

    - TbarWplusto2L2Nu
    - TbarWplusto4Q
    - TbarWplustoLNu2Q
    - TWminusto2L2Nu
    - TWminusto4Q
    - TWminustoLNu2Q

DY_LowMass:
  name: "DY M10to50"
  color: "kAzure+10"
  datasets:
    - DYto2E_M_10to50_amcatnloFXFX
    - DYto2Mu_M_10to50_amcatnloFXFX

DY_HighMass:
  name: "DY M50"
  cross_section_correction: 12/ 11  # NLO -> NNLO
  color: "kAzure+7"
  datasets:
    - DYto2E_M_50_0J_amcatnloFXFX
    - DYto2E_M_50_1J_amcatnloFXFX
    - DYto2E_M_50_2J_amcatnloFXFX

    - DYto2Mu_M_50_0J_amcatnloFXFX
    - DYto2Mu_M_50_1J_amcatnloFXFX
    - DYto2Mu_M_50_2J_amcatnloFXFX

    - DYto2Tau_M_50_0J_amcatnloFXFX
    - DYto2Tau_M_50_1J_amcatnloFXFX
    - DYto2Tau_M_50_2J_amcatnloFXFX

W:
  name: "W"
  color: "kGreen"  # eliminates need for plot.yaml
  datasets:
    - WtoLNu_0J_amcatnloFXFX
    - WtoLNu_1J_amcatnloFXFX
    - WtoLNu_2J_amcatnloFXFX

VV:
  name: "VV"
  color: "kGreen+2"  # eliminates need for inputs.yaml
  datasets:
    - WW
    - WZ
    - ZZ

XtoHHto2B2W_DoubleLepton:
  name: "XtoHHto2B2W_DoubleLepton"
  color: "kBlack"
  is_meta_process: true
  meta_setup:
    dataset_name_pattern: XtoYHto2B2Wto2B2L2Nu_MX_(\d+)_MY_125
    parameters: [ MASS ]
    process_name: XtoHHto2B2W_2L_${MASS}
    name_pattern: Xto2B2W 2L ${MASS} GeV (x50)
    to_plot:
      - [ '300' ]
      - [ '600' ]
      - [ '1000' ]
    plot_color: [ "kBlack", "kBlue", "kRed" ]
    channels: [ "eE", "eMu", "muMu" ]
  datasets:
    - XtoYHto2B2Wto2B2L2Nu_MX_300_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_400_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_500_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_550_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_600_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_650_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_700_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_800_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_900_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_1000_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_1200_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_1400_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_1600_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_1800_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_2000_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_2500_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_3000_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_3500_MY_125
    - XtoYHto2B2Wto2B2L2Nu_MX_4000_MY_125


XtoHHto2B2W_SingleLepton:
  name: "XtoHHto2B2W_SingleLepton"
  color: "kBlack"
  is_meta_process: true
  meta_setup:
    dataset_name_pattern: XtoYHto2B2Wto2B2Q1L1Nu_MX_(\d+)_MY_125
    parameters: [ MASS ]
    process_name: XtoHHto2B2W_1L_${MASS}
    name_pattern: Xto2B2W 1L ${MASS} GeV (x50)
    to_plot:
      - [ '300' ]
      - [ '600' ]
      - [ '1000' ]
    plot_color: [ "kBlack", "kBlue", "kRed" ]
    channels: [ "e", "mu" ]
  datasets:
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_300_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_400_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_500_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_550_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_600_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_650_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_700_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_800_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_900_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_1000_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_1200_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_1400_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_1600_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_1800_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_2000_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_2500_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_3000_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_3500_MY_125
    - XtoYHto2B2Wto2B2Q1L1Nu_MX_4000_MY_125

Data_Full:
  name: "Data"
  datasets:
    - EGamma0_Run2023C_v1
    - EGamma0_Run2023C_v2
    - EGamma0_Run2023C_v3
    - EGamma0_Run2023C_v4

    - EGamma1_Run2023C_v1
    - EGamma1_Run2023C_v2
    - EGamma1_Run2023C_v3
    - EGamma1_Run2023C_v4

    - Muon0_Run2023C_v1
    - Muon0_Run2023C_v2
    - Muon0_Run2023C_v3
    - Muon0_Run2023C_v4

    - Muon1_Run2023C_v1
    - Muon1_Run2023C_v2
    - Muon1_Run2023C_v3
    - Muon1_Run2023C_v4

    - MuonEG_Run2023C_v1
    - MuonEG_Run2023C_v2
    - MuonEG_Run2023C_v3
    - MuonEG_Run2023C_v4
