norm:
  PileUp_Lumi_MC:
    expression: weight_MC_Lumi_pu{scale}_rel  * final_weight
    name: CMS_pileup_{}
  MuonID_SF_Iso_ID:
    expression: weight_lep1_MuonID_SF_{muIso_WP_for_SF}PFIso_{muID_WP_for_SF}ID{scale}_rel * weight_lep2_MuonID_SF_{muIso_WP_for_SF}PFIso_{muID_WP_for_SF}ID{scale}_rel * final_weight
    name: CMS_eff_m_id_iso_{}
  MuonID_SF_ID:
    expression: weight_lep1_MuonID_SF_{muID_WP_for_SF}ID_Trk{scale}_rel * weight_lep2_MuonID_SF_{muID_WP_for_SF}ID_Trk{scale}_rel * final_weight
    name: CMS_eff_m_id_{}
  # MuonID_TightID:
  #   expression: weight_lep1_MuonID_SF_TightID_Trk{scale}_rel * weight_lep2_MuonID_SF_TightID_Trk{scale}_rel * final_weight
  #   name: MuonID_TightID_{}
  # MuonID_TightIDIso:
  #   expression: weight_lep1_MuonID_SF_LoosePFIso{scale}_rel * weight_lep2_MuonID_SF_LoosePFIso{scale}_rel * final_weight
  #   name: MuonID_TightIDIso_{}
  EleID_TightIDIso:
    expression: weight_lep1_EleSF_wp80iso_EleID{scale}_rel * weight_lep2_EleSF_wp80iso_EleID{scale}_rel * final_weight
    name: EleID_TightIDIso_{}
  EleID_TightIDNoIso:
    expression: weight_lep1_EleSF_wp80noiso_EleID{scale}_rel * weight_lep2_EleSF_wp80noiso_EleID{scale}_rel * final_weight
    name: EleID_TightIDNoIso_{}

  SingleEleTrg:
    expression: weight_lep1_TrgSF_singleEleWpTight_singleEle{scale}_rel * weight_lep2_TrgSF_singleEleWpTight_singleEle{scale}_rel * final_weight
    name: SingleEleTrg_{}
  SingleMuonTrg:
    expression: weight_lep1_TrgSF_singleIsoMu_IsoMu24{scale}_rel * weight_lep2_TrgSF_singleIsoMu_IsoMu24{scale}_rel * final_weight
    name: SingleMuonTrg_{}


shape:
  JER:
    name: CMS_scale_j_{}
  JES_Total:
    name: CMS_res_j_{}
  EleES:
    name: CMS_scale_e_{}
