fs_default:
  - /builds/cms-flaf/flaf_integration/output/HH_bbWW

analysis_config_area: config
compute_unc_variations: true
compute_unc_histograms: true
store_noncentral: true
phys_model: TestModel
variables:
  - lep1_pt
  - SingleLep_DeepHME_mass
  - DoubleLep_DeepHME_mass
  # - DNN_M0_Signal # Remove DNN for now while I move to new version
  # - DNNParametric_M250_Signal
  # - LinHMEDNN_linear_hme_dnn_m250
