fs_default:
  - /builds/cms-flaf/flaf_integration/output/HH_bbWW

analysis_config_area: config
compute_unc_variations: true
compute_unc_histograms: true
store_noncentral: true
phys_model: TestModel
variables:
  - lep1_pt
  - SingleLep_DeepHME_mass
  - DoubleLep_DeepHME_mass

  - name: lep1_pt_vs_eta
    vars: [ lep1_pt, lep1_eta ]
    plot_task: False
