Run3_Model:
  name: "Base model for Run 3"
  backgrounds:
    - TT
    - DY
    - ST
    - VV
    - W
  signals:
    - XtoHHto2B2W_SingleLepton
    - XtoHHto2B2W_DoubleLepton
  data:
    - Data_Full

OnlyData:
  name: "Only Data"
  backgrounds: [ ]
  signals: [ ]
  data:
    - Data_Full
