Run3_Model:
  name: "Base model for Run 3"
  backgrounds:
    - TT
    - DY
    - ST
    - VV
    - W
    - QCD_PT
  signals:
    - XtoHHto2B2W_SingleLepton
    - XtoHHto2B2W_DoubleLepton
  data:
    - Data_Full

OnlyData:
  name: "Only Data"
  backgrounds: [ ]
  signals: [ ]
  data:
    - Data_Full

TestModel:
  name: "Test model for CI"
  signals: # WARNING: for 2024 no signal sample available, using a file from bbtt signals..
    - custom_CI
