BaseTestModel:
  name: "Base Test Model"
  backgrounds:
    - TT_Inclusive
    - DY_HighMass
  signals:
    - GluGluToRadion_DoubleLepton

BaseModel:
  name: "Base Model"
  backgrounds:
    - TT
    - DY_LowMass
    - DY_HighMass
    - ST
    - VV
    - W
  # groups:
  #   mc_bkgs:
  #     - DY_stitched
  #     - VV
  signals:
    # - GluGluToRadion
    # - GluGluToBulkGraviton
    - GluGluToRadion_DoubleLepton
    - GluGluToRadion_SingleLepton
    - GluGluToBulkGraviton_DoubleLepton
    - GluGluToBulkGraviton_SingleLepton
  data:
    - Data_Full

OnlyData:
  name: "Only Data"
  backgrounds: [ ]
  signals: [ ]
  data:
    - Data_Full


Run3_Model:
  name: "Run3 Model"
  backgrounds:
    - TT
    - DY_LowMass
    - DY_HighMass
    - ST
    - VV
    - W
  signals:
    - XtoHHto2B2W_SingleLepton
    - XtoHHto2B2W_DoubleLepton
  data:
    - Data_Full
